// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCLSuLf9rUBVg0fx8ah5qdlT_zkxKmwM',
    appId: '1:723789969350:web:e2b4d294ec68ce428424c7',
    messagingSenderId: '723789969350',
    projectId: 'agarly-a8560',
    authDomain: 'agarly-a8560.firebaseapp.com',
    storageBucket: 'agarly-a8560.appspot.com',
    measurementId: 'G-YPH9WM3LT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4JX1WWQ2ze0fd7kZI--dMnd3pdovzBjc',
    appId: '1:723789969350:android:8d909fd724fa06d38424c7',
    messagingSenderId: '723789969350',
    projectId: 'agarly-a8560',
    storageBucket: 'agarly-a8560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85Xye4DahbKOUI2IRqbEMO3Fop3ygxBY',
    appId: '1:723789969350:ios:cc1b097eef4bd35b8424c7',
    messagingSenderId: '723789969350',
    projectId: 'agarly-a8560',
    storageBucket: 'agarly-a8560.appspot.com',
    iosBundleId: 'com.example.agarly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85Xye4DahbKOUI2IRqbEMO3Fop3ygxBY',
    appId: '1:723789969350:ios:9774ea2bb9199a3e8424c7',
    messagingSenderId: '723789969350',
    projectId: 'agarly-a8560',
    storageBucket: 'agarly-a8560.appspot.com',
    iosBundleId: 'com.example.agarly.RunnerTests',
  );
}
